python knn_marios_1.py
python nn_marios_1.py
python nn_marios_1_2.py
python nn_marios_1_3.py
python rf_marios_1.py
python rf_marios_1_2.py
python xgboost_marios_1.py
python xgboost_marios_1_2.py
python xgboost_marios_2.py
python xgboost_marios_4.py
python xgboost_marios_5.py
python xgboost_marios_7_2.py
python ada_marios_7_2.py
python ada_marios_7_3.py
python et_marios_1_2.py
python blender.py
